---
- name: Configuring apache2 using child playbooks
  hosts: all
  tasks:
   - name: call child playbooks
     include: "{{item}}"
     with_items:
      - installapache2child.yml
      - edit_indexhtml.yml
      - restart_apache2.yml
      - check_url_response.yml
...
